// The accounts that will be asked to be added after a new profile is added
const Map<String, bool> defaultIncome = {
  "Salary": true,
  "Freelance Income": true,
  "Business Profits": true,
  "Rental Income": true,
  "Dividends": false,
  "Stock Market Gains": false,
  "Crypto Gains": false,
  "Royalties": false,
  "Affiliate Marketing": false,
  "Social Media Revenue": false,
  "Interest on Savings": false,
  "Side Hustle Income": false,
  "Consulting Fees": false,
  "Tips and Bonuses": false,
  "Pension": false,
  "Government Benefits": false,
  "Alimony": false,
  "Lottery": false,
  "Selling Used Items": false,
};

const Map<String, bool> defaultExpense = {
  "Rent": true,
  "Mortgage": true,
  "Utilities": true,
  "Internet Bill": true,
  "Phone Bill": true,
  "Groceries": true,
  "Transportation": true,
  "Fuel": true,
  "Insurance": true,
  "Loan Repayment": true,
  "Dining Out": true,
  "Subscription": true,
  "Taxes": true,
  "Investments": true,
  "Healthcare": true,
  "Childcare": false,
  "Entertainment": false,
  "Travel": false,
  "Home Maintenance": false,
  "Vehicle Maintenance": false,
  "Gifts and Donations": false,
  "Personal Care": false,
  "Hobbies": false,
  "Pet Expenses": false,
  "Credit Card Payments": false,
  "Clothing and Accessories": false,
  "Work-Related Expenses": false,
  "Business Expenses": false,
  "Self-Improvement": false
};

const Map<String, bool> defaultCash = {"Cash": true};
