name: reminders_repository
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^19.5.0
  reminders_api: 
    path: ../reminders_api

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^3.0.1
